#!/bin/bash

feh --no-fehbg --bg-fill /home/pfouto/bin/wallpapers/kalns_C.jpg

killall -q polybar

while pgrep -u $UID -x polybar > /dev/null; do sleep 0.5; done

BAR="example"
for m in $(polybar --list-monitors | cut -d":" -f1); do
    export MONITOR=$m
    polybar --reload $BAR </dev/null >/var/tmp/polybar-$m.log 2>&1 &
    disown
    sleep 0.5
done

xinput --map-to-output "ELAN29E4:00 04F3:29E4" eDP-1
